### ISSUE TITLE
You don't need CGo for setting tty raw

### ISSUE THREAD

**Issue by tv42** [anaskhan96/sesh#1]
Here's a pure-Go example: https://godoc.org/github.com/u-root/u-root/pkg/termios#TTY.Raw

**Comment by anaskhan96** [comment]
@tv42 Thanks!
I came across different termios libraries in Go, and couldn't decide which one would be the simplest to use. On the other hand, the code in C was pretty small and something I had used very recently. Just decided to go with it.
